Repository Activiti/activiti-cloud-modeling-dependencies, pull requests merged in 2018-12, with the labels that each got.

#32 fix(versions): update Activiti/activiti-cloud-modeling-dependencies versions
  pom.xml
Labels: in progress, updatebot

#31 updatebot should use master branch
  .updatebot.yml
Labels: in progress

#33 fix(versions): update Activiti/activiti-cloud-modeling-dependencies versions
  pom.xml
Labels: in progress, updatebot

#34 fix(versions): update Activiti/activiti-cloud-modeling-dependencies versions
  pom.xml
Labels: in progress, updatebot

#35 fix(versions): update Activiti/activiti-cloud-modeling-dependencies versions
  pom.xml
Labels: in progress, updatebot

#36 fix(versions): update Activiti/activiti-cloud-modeling-dependencies versions
  pom.xml
Labels: in progress, updatebot

#37 fix(versions): update Activiti/activiti-cloud-modeling-dependencies versions
  pom.xml
Labels: in progress, updatebot

#39 fix(versions): update Activiti/activiti-cloud-modeling-dependencies versions
  pom.xml
Labels: updatebot

#42 fix(versions): update Activiti/activiti-cloud-modeling-dependencies versions
  pom.xml
Labels: updatebot

#43 fix(versions): update Activiti/activiti-cloud-modeling-dependencies versions
  pom.xml
Labels: updatebot

#44 fix(versions): update Activiti/activiti-cloud-modeling-dependencies versions
  pom.xml
Labels: updatebot
