Repository Activiti/activiti-cloud-modeling-dependencies, pull requests merged in 2018-11, with the labels that each got.

#11 update org.activiti.cloud.modeling:activiti-cloud-org-dependencies to 7.0.29
  pom.xml
Labels: updatebot

#12 update org.activiti.cloud.process.model:activiti-cloud-process-model-dependencies to 7.0.24
  pom.xml
Labels: updatebot

#16 Configure Updatebot single PR for cloud-dependencies tests and automatic merge with Mergify
  .mergify.yml
  dependencies-tests/pom.xml
  dependencies/pom.xml
  pom.xml
Labels: enhancement, in progress

#15 update org.activiti.cloud.modeling.build:activiti-cloud-modeling-parent to 7.0.3
  pom.xml
Labels: in progress, updatebot

#19 fix: incorrect activiti-cloud-modeling-dependencies artifactId
  dependencies/pom.xml
Labels: enhancement, in progress

#22 Refactor activiti-cloud-modeling-dependencies-tests module
  .mergify.yml
  dependencies-tests/pom.xml
  dependencies/pom.xml
  pom.xml
Labels: enhancement, in progress

#23 fix(versions): update Activiti/activiti-cloud-modeling-dependencies versions
  pom.xml
Labels: in progress, updatebot

#24 fix(versions): update Activiti/activiti-cloud-modeling-dependencies versions
  pom.xml
Labels: in progress, updatebot

#25 fix(versions): update Activiti/activiti-cloud-modeling-dependencies versions
  Jenkinsfile
  pom.xml
Labels: in progress, updatebot

#27 fix(versions): update Activiti/activiti-cloud-modeling-dependencies versions
  pom.xml
Labels: in progress, updatebot

#28 fix(versions): update Activiti/activiti-cloud-modeling-dependencies versions
  pom.xml
Labels: in progress, updatebot

#29 fix(versions): update Activiti/activiti-cloud-modeling-dependencies versions
  pom.xml
Labels: in progress, updatebot

#30 fix(versions): update Activiti/activiti-cloud-modeling-dependencies versions
  pom.xml
Labels: in progress, updatebot
